[package]
name = "ann-search-rs"
version = "0.2.0"
edition = "2021"
authors = ["Gregor Lueg <gregorlueg@me.com>"]
license = "MIT"
repository = "https://github.com/GregorLueg/ann-search-rs"
description = "Various approximate nearest neighbour searches in Rust with emphasis for single cell applications."

[lib]
name = "ann_search_rs"
path = "src/lib.rs"

[profile.release]
lto = true
codegen-units = 1


[dependencies]
approx = "0.5.1"
clap = { version = "4.5.53", features = ["derive"] }
faer = "0.23.2"
fixedbitset = "0.5.7"
num-traits = "0.2.19"
parking_lot = "0.12.5"
rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"
rustc-hash = "2.1.1"
thousands = "0.2.0"
