[package]
name = "ann-search-rs"
version = "0.1.1"
edition = "2021"
authors = ["Gregor Lueg <gregorlueg@me.com>"]
license = "MIT"
repository = "https://github.com/GregorLueg/node2vec-rs"
description = "Various approximate nearest neighbour searches in Rust."

[lib]
name = "ann_search_rs"
path = "src/lib.rs"

[dependencies]
approx = "0.5.1"
faer = "0.23.2"
num-traits = "0.2.19"
rand = "0.9.2"
rayon = "1.11.0"
